[package]
name = "display-in-gitlab-merge-request"
version = "0.1.0"
authors = ["Damien Cuenot <damien.cuenot@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
anyhow = "1.0"
serde = "1.0"
serde_derive = "1.0"
Inflector = "0.5"

[dev-dependencies]
proptest = "0.9"